import { useEffect, useState } from 'react'
import { useWorkspaceStore } from '@/store/workspaceStore'
import { useNotifStore } from '@/store/useNotifStore'
import { forgeHealth, forgeStylize } from '@/lib/forgeClient'
import { mintSessionCapability, verifySessionCapability } from '@/lib/capabilityToken'
import { MCP_HANDLERS, MCP_TOOLS } from '@/lib/mcpTools'
import type { SurfaceId } from '@/types'

/**
 * DevMenu — ⌘D-gated developer menu (inactive until opened).
 *
 * Per the dev-menu research: renders a small floating control that does
 * nothing until opened; keyboard-shortcut toggled (⌘D / Ctrl+D), Escape to
 * close, reduced-motion aware. Contents are the P31-portal-specific tools:
 * forge health + raw stylize, PQC token debug, starfield mods, MCP inventory.
 */
export function DevMenu() {
  const devOpen = useWorkspaceStore((s) => s.devOpen)
  const setDevOpen = useWorkspaceStore((s) => s.setDevOpen)

  useEffect(() => {
    if (!devOpen) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setDevOpen(false)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [devOpen, setDevOpen])

  if (!devOpen) return null

  return (
    <div className="dev-menu" role="dialog" aria-label="Developer menu">
      <div className="dev-menu__head">
        <span>Developer menu</span>
        <button type="button" className="dev-menu__close" onClick={() => setDevOpen(false)} aria-label="Close">
          ×
        </button>
      </div>
      <div className="dev-menu__body">
        <ForgePane />
        <TokenPane />
        <StarfieldPane />
        <McpPane />
      </div>
    </div>
  )
}

function ForgePane() {
  const [health, setHealth] = useState<{ status: string; version?: string } | null>(null)
  const [stylize, setStylize] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    forgeHealth()
      .then(setHealth)
      .catch(() => setHealth({ status: 'offline' }))
  }, [])

  async function runStylize() {
    setBusy(true)
    setStylize(null)
    try {
      const req = {
        kind: 'memo' as const,
        theme: 'scene' as const,
        title: 'Dev probe',
        body: [
          { type: 'h1' as const, text: 'Dev menu probe' },
          { type: 'para' as const, text: 'Generated by the P31 Forge from the dev menu.' },
          { type: 'evidence' as const, claim: 'Generated by P31 Forge', value: 'themed .docx', source: 'p31-forge.trimtab-signal.workers.dev', verified: '2026-09-23' },
        ],
      }
      const { bytes, filename } = await forgeStylize(req)
      setStylize(`ok · ${filename} · ${bytes.byteLength} bytes`)
    } catch (e) {
      setStylize(`error: ${(e as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="dev-pane">
      <h3>Forge</h3>
      <p>
        health:{' '}
        <span className={health?.status === 'ok' ? 'setup-ok' : 'setup-err'}>
          {health?.status ?? 'checking…'}
          {health?.version ? ` v${health.version}` : ''}
        </span>
      </p>
      <button type="button" className="btn btn-glass btn-sm" onClick={runStylize} disabled={busy}>
        {busy ? 'stylizing…' : 'raw stylize test'}
      </button>
      {stylize && <p className="setup-mono">{stylize}</p>}
    </div>
  )
}

function TokenPane() {
  const setSessionToken = useWorkspaceStore((s) => s.setSessionToken)
  const clearSessionToken = useWorkspaceStore((s) => s.clearSessionToken)
  const sessionToken = useWorkspaceStore((s) => s.sessionToken)
  const tokenFingerprint = useWorkspaceStore((s) => s.tokenFingerprint)
  const [result, setResult] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  async function mint() {
    setBusy(true)
    setResult(null)
    try {
      const cap = await mintSessionCapability('did:key:workspace-dev')
      setSessionToken(cap.token, cap.fingerprint)
      setResult(`minted · fingerprint ${cap.fingerprint.slice(0, 12)}…`)
    } catch (e) {
      setResult(`error: ${(e as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  async function verify() {
    if (!sessionToken) { setResult('no token to verify'); return }
    const valid = await verifySessionCapability(sessionToken)
    setResult(valid ? 'valid · self-contained PQCAP' : 'INVALID')
  }

  return (
    <div className="dev-pane">
      <h3>Session token</h3>
      <p>
        state:{' '}
        <span className={sessionToken ? 'setup-ok' : 'setup-dim'}>
          {sessionToken ? `minted${tokenFingerprint ? ` · ${tokenFingerprint.slice(0, 12)}…` : ''}` : 'none'}
        </span>
      </p>
      <div className="dev-pane__row">
        <button type="button" className="btn btn-glass btn-sm" onClick={mint} disabled={busy}>
          {busy ? 'minting…' : 'mint'}
        </button>
        <button type="button" className="btn btn-glass btn-sm" onClick={verify}>
          verify
        </button>
        {sessionToken && (
          <button type="button" className="btn btn-glass btn-sm" onClick={clearSessionToken}>
            clear
          </button>
        )}
      </div>
      {result && <p className="setup-mono">{result}</p>}
    </div>
  )
}

function StarfieldPane() {
  const starfield = useWorkspaceStore((s) => s.starfield)
  const reseedStarfield = useWorkspaceStore((s) => s.reseedStarfield)
  const notify = useNotifStore((s) => s.notify)

  return (
    <div className="dev-pane">
      <h3>Starfield mods</h3>
      <p className="setup-mono">
        seed {starfield.seed} · {starfield.count} stars · {starfield.twinkleSpeed.toFixed(1)}x · flare{' '}
        {starfield.flareCount} {starfield.flaring ? 'on' : 'off'}
      </p>
      <div className="dev-pane__row">
        <button type="button" className="btn btn-glass btn-sm" onClick={reseedStarfield}>
          re-seed
        </button>
        <button
          type="button"
          className="btn btn-glass btn-sm"
          onClick={() => notify({ kind: 'milestone', title: 'Burst probe', body: 'This notification flares the starfield.', burst: true })}
        >
          fire burst
        </button>
      </div>
    </div>
  )
}

function McpPane() {
  const surfaces = Object.keys(MCP_TOOLS) as SurfaceId[]
  return (
    <div className="dev-pane">
      <h3>MCP tool inventory</h3>
      <ul className="dev-list">
        {surfaces.map((s) => (
          <li key={s} className="setup-mono">
            {s} → {MCP_TOOLS[s]} · {MCP_HANDLERS[s]}
          </li>
        ))}
      </ul>
    </div>
  )
}

export default DevMenu