import { useState } from 'react'
import { MCP_TOOLS } from '@/lib/mcpTools'
import { dispatch } from '@/features/kernel/kernel'
import { forgeStylize } from '@/lib/forgeClient'
import { pickleName } from '@/lib/pickleNames'

interface WorkspaceFile {
  id: string
  name: string
  kind: 'doc' | 'sheet' | 'slide' | 'file' | 'key'
  size: string
  modified: string
  owner: string
  mime: string
}

// Pickle labels only — no human names.
const SEED: WorkspaceFile[] = [
  { id: 'f1', name: 'Q3 Roadmap.pdoc', kind: 'doc', size: '24 KB', modified: 'Today 11:20 AM', owner: pickleName('caregiver-one'), mime: 'application/p31-doc' },
  { id: 'f2', name: 'Family Budget.psheet', kind: 'sheet', size: '142 KB', modified: 'Sep 21, 2026', owner: pickleName('caregiver-two'), mime: 'application/p31-sheet' },
  { id: 'f3', name: 'Vision Deck.pslide', kind: 'slide', size: '4.2 MB', modified: 'Sep 19, 2026', owner: pickleName('young-one'), mime: 'application/p31-slide' },
  { id: 'f4', name: 'Backup_Key_Node.pem', kind: 'key', size: '2 KB', modified: 'Sep 01, 2026', owner: pickleName('caregiver-one'), mime: 'application/x-pem-file' },
]

const KIND_ICON: Record<WorkspaceFile['kind'], string> = {
  doc: '📄', sheet: '📊', slide: '📽️', file: '📁', key: '🔑',
}

export function DriveSurface() {
  const [selectedId, setSelectedId] = useState(SEED[0]!.id)
  const [prompt, setPrompt] = useState('')
  const [busy, setBusy] = useState(false)
  const [status, setStatus] = useState<string | null>(null)
  const selected = SEED.find((f) => f.id === selectedId)!

  async function handleGenerate() {
    const title = prompt.trim()
    if (!title || busy) return
    setBusy(true)
    setStatus(null)
    try {
      const { plan, pack: routed } = dispatch(title)
      const { kind, theme: kindTheme } = routed

      const req = {
        kind,
        theme: kindTheme,
        title,
        body: [
          { type: 'h1' as const, text: title },
          { type: 'para' as const, text: `Generated by the P31 Forge from the prompt: “${title}”.` },
          { type: 'evidence' as const, claim: 'Generated by P31 Forge', value: 'themed .docx', source: 'p31-forge.trimtab-signal.workers.dev', verified: '2026-09-23' },
        ],
      }

      const { bytes, filename } = await forgeStylize(req)
      const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)

      setStatus(`Generated ${filename} · pipeline: ${plan.join(' → ')}.`)
      setPrompt('')
    } catch (e) {
      setStatus(`Failed: ${e instanceof Error ? e.message : String(e)}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="surface-panel active" data-mcp-tool={MCP_TOOLS.drive} aria-label="Drive surface">
      <div className="drive-layout">
        <div className="drive-toolbar">
          <div className="drive-chips">
            <div className="chip active">All Files</div>
            <div className="chip">Recent</div>
            <div className="chip">Shared</div>
            <div className="chip">Trash</div>
          </div>
          <div className="drive-forge" data-mcp-tool="driveForge" data-mcp-state="ready">
            <input
              type="text"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') void handleGenerate() }}
              placeholder="Describe a document to generate…"
              aria-label="Document description"
            />
            <button className="btn btn-primary" type="button" onClick={() => void handleGenerate()} disabled={busy}>
              {busy ? 'Generating…' : 'Generate'}
            </button>
          </div>
        </div>

        {status && (
          <div className="drive-status" data-mcp-tool="driveForgeStatus" data-mcp-state="ready" role="status">
            {status}
          </div>
        )}

        <div className="drive-content">
          <div className="drive-grid">
            {SEED.map((f) => (
              <button
                key={f.id}
                type="button"
                className={`file-card ${f.id === selectedId ? 'selected' : ''}`}
                onClick={() => setSelectedId(f.id)}
              >
                <div className="file-icon">{KIND_ICON[f.kind]}</div>
                <div style={{ fontWeight: 600 }}>{f.name}</div>
                <div style={{ fontSize: 12, color: 'var(--p31-cloud)' }}>P31 {f.kind} · {f.size}</div>
              </button>
            ))}
          </div>

          <aside className="drive-preview">
            <div style={{ fontSize: 48, textAlign: 'center' }}>{KIND_ICON[selected.kind]}</div>
            <h3 style={{ fontSize: 'var(--p31-text-lg)', textAlign: 'center' }}>{selected.name}</h3>

            <div style={{ borderTop: '1px solid var(--p31-glass-border)', paddingTop: 16, display: 'flex', flexDirection: 'column', gap: 8, fontSize: 13 }}>
              <div><span style={{ color: 'var(--p31-cloud)' }}>Type:</span> {selected.mime}</div>
              <div><span style={{ color: 'var(--p31-cloud)' }}>Size:</span> {selected.size}</div>
              <div><span style={{ color: 'var(--p31-cloud)' }}>Modified:</span> {selected.modified}</div>
              <div><span style={{ color: 'var(--p31-cloud)' }}>Owner:</span> {selected.owner}</div>
              <div><span style={{ color: 'var(--p31-cloud)' }}>Storage Node:</span> Local NVMe (Encrypted)</div>
            </div>

            <button className="btn btn-primary" type="button" style={{ marginTop: 'auto' }}>Open File</button>
          </aside>
        </div>
      </div>
    </section>
  )
}

export default DriveSurface