#!/usr/bin/env node
/**
 * Auto-generate CSF3 stories for all primitives from the canonical registry.
 * Regenerate after adding a primitive: `pnpm gen:stories`.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/primitives');

/** registry: file → [exportName, argTypes overrides] */
const REGISTRY: Record<string, {
  args?: Record<string, unknown>;
  argTypes?: Record<string, unknown>;
  export?: string | null;
  renderExtras?: string;
  storyOnly?: boolean;
}> = {
  Button: {
    args: { children: 'Save changes', variant: 'primary', size: 'md', isLoading: false, disabled: false },
    argTypes: { variant: { control: 'radio', options: ['primary', 'secondary', 'danger', 'ghost'] }, size: { control: 'radio', options: ['sm', 'md', 'lg'] } },
  },
  Input: { args: { label: 'Email', placeholder: 'you@example.org', error: '', hint: '' } },
  Select: { args: { label: 'Tier', options: [{ value: '1', label: 'One' }, { value: '2', label: 'Two' }] } },
  Checkbox: { args: { label: 'Subscribe to care digests', indeterminate: false } },
  Radio: { export: 'RadioGroup', args: { value: 'a', ariaLabel: 'Choice', options: [{ value: 'a', label: 'Alpha' }, { value: 'b', label: 'Beta' }] }, renderExtras: "const [v, setV] = useState(args.value);\n  args.value = v; args.onChange = setV;" },
  Card: { args: { padding: 'md', interactive: true, children: 'Glass card content' }, argTypes: { padding: { control: 'radio', options: ['none', 'sm', 'md', 'lg', 'xl'] } } },
  Badge: { args: { tone: 'success', children: 'online' }, argTypes: { tone: { control: 'radio', options: ['success', 'warning', 'error', 'info', 'neutral'] } } },
  Toast: { export: null /* provider pattern — documented story below */ },
  Modal: { storyOnly: true },
  Tooltip: { args: { content: 'You can do this', placement: 'top', children: 'Affirm' }, argTypes: { placement: { control: 'radio', options: ['top', 'bottom'] } } },
  Dropdown: { storyOnly: true },
  Spinner: { args: { size: 'md', label: 'Loading' }, argTypes: { size: { control: 'radio', options: ['sm', 'md', 'lg'] } } },
};

for (const [file, spec] of Object.entries(REGISTRY)) {
  if (spec.storyOnly || spec.export === null) continue;
  const name = spec.export ?? file;
  const needsState = Boolean(spec.renderExtras);
  const imports = needsState ? "import { useState } from 'react';\n" : '';
  const renderBody = spec.renderExtras ? `import ${name} from './${file}';` : '';

  const story = `${needsState ? "import { useState } from 'react';" : ''}
import type { Meta, StoryObj } from '@storybook/react';
import { ${spec.export ?? name}${file === 'Radio' ? '' : ''} } from './${file}';
// GENERATED by scripts/gen-stories.mts — regenerate with \`pnpm gen:stories\`

const meta: Meta<typeof ${name}> = {
  title: 'Primitives/${name}',
  component: ${name},
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: ${JSON.stringify(spec.args, null, 2)} as never,
${spec.argTypes ? `  argTypes: ${JSON.stringify(spec.argTypes)},` : ''}
};
`;
  writeFileSync(join(OUT, `${file}.stories.tsx`), story);
}

// Hand-tuned interactive stories that need real state/providers
writeFileSync(
  join(OUT, 'Toast.stories.tsx'),
  `import type { Meta, StoryObj } from '@storybook/react';
import { ToastProvider, useToast } from './Toast';
import { Button } from './Button';

function Demo() {
  const { toast } = useToast();
  return (
    <div style={{ display: 'flex', gap: 8 }}>
      <Button onClick={() => toast('Care entry saved', { tone: 'success' })}>Success</Button>
      <Button variant="danger" onClick={() => toast('Sync failed — retry?', { tone: 'error', duration: 0 })}>Error sticky</Button>
      <Button variant="ghost" onClick={() => toast('Heads up', { tone: 'warning' })}>Warning</Button>
    </div>
  );
}

const meta: Meta = { title: 'Primitives/Toast', tags: ['autodocs'] };
export default meta;
export const Tones: StoryObj = { render: () => <ToastProvider><Demo /></ToastProvider> };
`
);

writeFileSync(
  join(OUT, 'Modal.stories.tsx'),
  `import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Modal } from './Modal';
import { Button } from './Button';

function Demo() {
  const [open, setOpen] = useState(true);
  return (
    <>
      <Button onClick={() => setOpen(true)}>Open</Button>
      <Modal open={open} onClose={() => setOpen(false)} title="Confirm action"
        actions={<><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => setOpen(false)}>Confirm</Button></>}>
        This dialog is fully opaque in crisis mode.
      </Modal>
    </>
  );
}

const meta: Meta = { title: 'Primitives/Modal', tags: ['autodocs'] };
export default meta;
export const Interactive: StoryObj = { render: () => <Demo /> };
`
);

writeFileSync(
  join(OUT, 'Dropdown.stories.tsx'),
  `import type { Meta, StoryObj } from '@storybook/react';
import { Dropdown } from './Dropdown';
import { Button } from './Button';

const meta: Meta = { title: 'Primitives/Dropdown', tags: ['autodocs'] };
export default meta;
export const Menu: StoryObj = {
  render: () => (
    <Dropdown
      ariaLabel="Actions"
      trigger={({ open }) => <Button variant="secondary">{open ? '▲' : '▼'} Actions</Button>}
      items={[{ value: 'edit', label: 'Edit' }, { value: 'share', label: 'Share' }, { value: 'del', label: 'Delete', disabled: true }]}
      onSelect={(v) => console.log(v)}
    />
  ),
};
`
);

console.log('✅ stories generated for primitives');
