#!/usr/bin/env node
/**
 * Token compiler — emits CSS custom properties from src/tokens/*.ts.
 * Outputs (deterministic, committed):
 *   src/generated/color-palette.css   ramp + semantic vars, dark-mode inversion
 *   src/generated/spoon-ladder.css    [data-spoons] motion/blur/opacity overrides
 *   src/generated/typography-scale.css type scale + weight tokens
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colorRamps, RAMP_STEPS, RAMP_BASE_INDEX } from '../src/tokens/color.js';
import { fontStacks, fontWeightTokens, typographyScale } from '../src/tokens/typography.js';
import { motionTokens, spoonLadder } from '../src/tokens/motion.js';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/generated');
mkdirSync(OUT, { recursive: true });

const banner = (name: string) =>
  `/* GENERATED by scripts/gen-tokens.mts — source: src/tokens/${name}. Do not edit. */\n`;

// ── color-palette.css ────────────────────────────────────────────
let css = banner('color.ts');
for (const [ramp, shades] of Object.entries(colorRamps)) {
  shades.forEach((hex, i) => {
    const step = RAMP_STEPS[i] ?? '950';
    css += `--p31-${ramp}-${step}: ${hex};\n`;
    if (i === RAMP_BASE_INDEX) css += `--p31-${ramp}: ${hex};\n`;
  });
}
css += `\n/* Semantic aliases (light default) */\n`;
css += `:root {\n  color-scheme: light dark;\n}\n`;
css += `\n@media (prefers-color-scheme: dark) {\n:root {\n`;
css += `  --p31-accent-50: var(--p31-neutral-900);\n`;
css += `}\n}\n`;
writeFileSync(join(OUT, 'color-palette.css'), css);

// ── spoon-ladder.css ─────────────────────────────────────────────
let ladder = banner('motion.ts');
ladder += `:root {\n`;
ladder += `  --p31-motion-fast: ${motionTokens.fast};\n`;
ladder += `  --p31-motion-normal: ${motionTokens.normal};\n`;
ladder += `  --p31-motion-slow: ${motionTokens.slow};\n`;
ladder += `  --p31-motion-easing-in: ${motionTokens.easeIn};\n`;
ladder += `  --p31-motion-easing-out: ${motionTokens.easeOut};\n`;
ladder += `  --p31-motion-easing-inout: ${motionTokens.easeInOut};\n`;
ladder += `}\n`;
for (const s of spoonLadder) {
  ladder += `\n[data-spoons="${s.level}"] {\n`;
  ladder += `  --p31-motion-fast: ${s.motion};\n`;
  ladder += `  --p31-motion-normal: ${s.motion};\n`;
  ladder += `  --p31-motion-slow: ${s.level <= 1 ? '0ms' : motionTokens.slow};\n`;
  ladder += `  --p31-glass-blur: ${s.blur};\n`;
  if (s.level <= 1) {
    ladder += `  --p31-glass-bg: var(--p31-surface);\n`;
    ladder += `  --p31-glass-bg-strong: var(--p31-surface);\n`;
    ladder += `  --p31-text-secondary: var(--p31-text);\n`;
  }
  ladder += `}\n`;
}
writeFileSync(join(OUT, 'spoon-ladder.css'), ladder);

// ── typography-scale.css ─────────────────────────────────────────
let type = banner('typography.ts');
type += `:root {\n`;
type += `  --p31-font-weight-body: ${fontWeightTokens.body};\n`;
type += `  --p31-font-weight-emphasis: ${fontWeightTokens.emphasis};\n`;
for (const [k, v] of Object.entries(typographyScale)) type += `  --p31-type-${k}: ${v};\n`;
type += `  --p31-font-stack-sans: ${fontStacks.sans};\n`;
type += `  --p31-font-stack-mono: ${fontStacks.mono};\n`;
type += `}\n`;
writeFileSync(join(OUT, 'typography-scale.css'), type);

console.log('✅ generated:', ['color-palette.css', 'spoon-ladder.css', 'typography-scale.css'].join(', '));
