import { useState } from 'react';
import { useQpjStore } from '../../store/useQpjStore';
import { forgeStylize, type ForgeTheme } from './forgeClient';
import { dispatch } from '../kernel/kernel';
import './drive.css';

interface DriveFile {
  id: string
  name: string
  type: string
  icon: string
  size: string
  date: string
  mcpTool: string
}

const INITIAL_FILES: DriveFile[] = [
  { id: 'f1', name: 'Q3 Roadmap.pdoc', type: 'P31 Doc', icon: '📄', size: '24 KB', date: 'Today 11:20 AM', mcpTool: 'driveFile' },
  { id: 'f2', name: 'Family Budget.psheet', type: 'P31 Sheet', icon: '📊', size: '142 KB', date: 'Sep 21, 2026', mcpTool: 'driveFile' },
  { id: 'f3', name: 'Vision Deck.pslide', type: 'P31 Slide', icon: '📽️', size: '4.2 MB', date: 'Sep 19, 2026', mcpTool: 'driveFile' },
  { id: 'f4', name: 'Backup_Key_Node.pem', type: 'Security Key', icon: '🔑', size: '2 KB', date: 'Sep 01, 2026', mcpTool: 'driveFile' },
]

/** Forge-generated documents land here (the family pipeline → forge → docx). */
const FORGE_DOCS: DriveFile[] = [
  { id: 'g1', name: 'Willow_IEP_Request.docx', type: 'Forge Doc', icon: '🧾', size: '11 KB', date: 'Today 12:05 PM', mcpTool: 'driveForgeDoc' },
  { id: 'g2', name: 'School_Letter_HashChain.docx', type: 'Forge Doc', icon: '🧾', size: '10 KB', date: 'Today 12:04 PM', mcpTool: 'driveForgeDoc' },
]

export function DriveSurface() {
  const [selected, setSelected] = useState<DriveFile>(INITIAL_FILES[0])
  const [tab, setTab] = useState<'all' | 'forge'>('all')
  const [forgeDocs, setForgeDocs] = useState<DriveFile[]>(FORGE_DOCS)
  const [prompt, setPrompt] = useState('')
  const [theme, setTheme] = useState<ForgeTheme>('hub')
  const [busy, setBusy] = useState(false)
  const [status, setStatus] = useState<string | null>(null)
  const spoons = useQpjStore((s) => s.spoons)
  const lowSpoons = spoons <= 2
  const files = tab === 'forge' ? forgeDocs : [...forgeDocs, ...INITIAL_FILES]

  const pick = (f: DriveFile) => setSelected(f)

  const handleGenerate = async () => {
    const title = prompt.trim()
    if (!title || busy) return
    setBusy(true)
    setStatus(null)
    try {
      // The kernel routes the intent deterministically (no LLM).
      const { plan, pack: routed } = dispatch(title)
      const { kind, theme: kindTheme } = routed

      const pack = {
        kind,
        theme: kind === 'report' ? kindTheme : theme,
        title,
        date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
        body: [
          { type: 'h1' as const, text: title },
          { type: 'para' as const, text: `This document was generated by the family's Forge from the Drive prompt: “${title}”.` },
          {
            type: 'evidence' as const,
            claim: 'Generated by P31 Forge',
            value: 'themed .docx',
            source: 'p31-forge.trimtab-signal.workers.dev',
            verified: '2026-09-23',
          },
        ],
      }
      const { bytes, filename } = await forgeStylize(pack)
      const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(url)

      const newFile: DriveFile = {
        id: `g-${Date.now()}`,
        name: filename,
        type: 'Forge Doc',
        icon: '🧾',
        size: `${Math.max(1, Math.round(bytes.byteLength / 1024))} KB`,
        date: 'Just now',
        mcpTool: 'driveForgeDoc',
      }
      setForgeDocs((d) => [newFile, ...d])
      setStatus(`Generated ${filename} · pipeline: ${plan.join(' → ')}.`)
      setPrompt('')
    } catch (e) {
      setStatus(`Failed: ${e instanceof Error ? e.message : String(e)}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="drive-surface" data-mcp-tool="driveSurface" data-mcp-state="ready" aria-label="Drive">
      <div className="drive-surface__toolbar">
        <div className="drive-surface__chips">
          <button type="button" className={`chip${tab === 'all' ? ' is-active' : ''}`} onClick={() => setTab('all')}>All Files</button>
          <button type="button" className={`chip${tab === 'forge' ? ' is-active' : ''}`} onClick={() => setTab('forge')}>Forge Docs</button>
          <button type="button" className="chip">Recent</button>
          <button type="button" className="chip">Trash</button>
        </div>
        <div className="drive-surface__forge" data-mcp-tool="driveForge" data-mcp-state={lowSpoons ? 'quiet' : 'ready'}>
          {!lowSpoons && (
            <>
              <select
                value={theme}
                onChange={(e) => setTheme(e.target.value as ForgeTheme)}
                aria-label="Forge theme"
                className="drive-surface__theme"
              >
                <option value="hub">Warm · hub</option>
                <option value="scene">Dark · scene</option>
              </select>
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') void handleGenerate() }}
                placeholder="Describe a document to generate…"
                aria-label="Document description"
                className="drive-surface__prompt"
              />
              <button type="button" className="btn btn-primary" onClick={() => void handleGenerate()} disabled={busy}>
                {busy ? 'Generating…' : 'Generate'}
              </button>
            </>
          )}
        </div>
      </div>

      {status && (
        <div className="drive-surface__status" data-mcp-tool="driveForgeStatus" data-mcp-state="ready">
          {status}
        </div>
      )}

      <div className="drive-surface__content">
        <div className="drive-surface__grid">
          {files.map((f) => (
            <button
              key={f.id}
              type="button"
              className={`file-card${selected.id === f.id ? ' is-selected' : ''}`}
              data-mcp-tool={f.mcpTool}
              data-mcp-state="ready"
              onClick={() => pick(f)}
              aria-label={f.name}
            >
              <span className="file-card__icon" aria-hidden="true">{f.icon}</span>
              <span className="file-card__name">{f.name}</span>
              <span className="file-card__meta">{f.type} · {f.size}</span>
            </button>
          ))}
        </div>

        <aside className="drive-surface__preview">
          <div className="drive-surface__preview-icon" aria-hidden="true">{selected.icon}</div>
          <h3 className="drive-surface__preview-name">{selected.name}</h3>
          <dl className="drive-surface__preview-meta">
            <div><dt>Type</dt><dd>{selected.type}</dd></div>
            <div><dt>Size</dt><dd>{selected.size}</dd></div>
            <div><dt>Modified</dt><dd>{selected.date}</dd></div>
            <div><dt>Storage Node</dt><dd>Local NVMe (Encrypted)</dd></div>
          </dl>
          <button type="button" className="btn btn-primary">Open File</button>
        </aside>
      </div>
    </section>
  )
}

export default DriveSurface