
import type { Meta, StoryObj } from '@storybook/react';
import { Badge } from './Badge';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Badge> = {
  title: 'Primitives/Badge',
  component: Badge,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "tone": "success",
  "children": "online"
} as never,
  argTypes: {"tone":{"control":"radio","options":["success","warning","error","info","neutral"]}},
};
