
import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Button> = {
  title: 'Primitives/Button',
  component: Button,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "children": "Save changes",
  "variant": "primary",
  "size": "md",
  "isLoading": false,
  "disabled": false
} as never,
  argTypes: {"variant":{"control":"radio","options":["primary","secondary","danger","ghost"]},"size":{"control":"radio","options":["sm","md","lg"]}},
};
