
import type { Meta, StoryObj } from '@storybook/react';
import { Card } from './Card';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Card> = {
  title: 'Primitives/Card',
  component: Card,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "padding": "md",
  "interactive": true,
  "children": "Glass card content"
} as never,
  argTypes: {"padding":{"control":"radio","options":["none","sm","md","lg","xl"]}},
};
