
import type { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from './Checkbox';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Checkbox> = {
  title: 'Primitives/Checkbox',
  component: Checkbox,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "label": "Subscribe to care digests",
  "indeterminate": false
} as never,

};
