
import type { Meta, StoryObj } from '@storybook/react';
import { Input } from './Input';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Input> = {
  title: 'Primitives/Input',
  component: Input,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "label": "Email",
  "placeholder": "you@example.org",
  "error": "",
  "hint": ""
} as never,

};
