import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { RadioGroup } from './Radio';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof RadioGroup> = {
  title: 'Primitives/RadioGroup',
  component: RadioGroup,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "value": "a",
  "ariaLabel": "Choice",
  "options": [
    {
      "value": "a",
      "label": "Alpha"
    },
    {
      "value": "b",
      "label": "Beta"
    }
  ]
} as never,

};
