
import type { Meta, StoryObj } from '@storybook/react';
import { Select } from './Select';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Select> = {
  title: 'Primitives/Select',
  component: Select,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "label": "Tier",
  "options": [
    {
      "value": "1",
      "label": "One"
    },
    {
      "value": "2",
      "label": "Two"
    }
  ]
} as never,

};
