
import type { Meta, StoryObj } from '@storybook/react';
import { Spinner } from './Spinner';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Spinner> = {
  title: 'Primitives/Spinner',
  component: Spinner,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "size": "md",
  "label": "Loading"
} as never,
  argTypes: {"size":{"control":"radio","options":["sm","md","lg"]}},
};
