
import type { Meta, StoryObj } from '@storybook/react';
import { Tooltip } from './Tooltip';
// GENERATED by scripts/gen-stories.mts — regenerate with `pnpm gen:stories`

const meta: Meta<typeof Tooltip> = {
  title: 'Primitives/Tooltip',
  component: Tooltip,
  tags: ['autodocs'],
};
export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
  "content": "You can do this",
  "placement": "top",
  "children": "Affirm"
} as never,
  argTypes: {"placement":{"control":"radio","options":["top","bottom"]}},
};
